### ISSUE TITLE
naexp05 - Pre/post test - cross-posting blogs to medium

### ISSUE THREAD

**Issue by ejregithub** [mozilla/blogdotmozilladotorg#12]
## Description

Enable cross-posting of Blogs from WP to medium
[manapage](https://mana.mozilla.org/wiki/display/EN/Cross-posting+Blogs+to+medium)
[Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1543192)
https://trello.com/c/dfZ54iZZ

Driving Insight: We believe that a custom content block added to the Wordpress parent blog theme that allows blog editors to add call-out content that is distinct from the body content would help users find more content that is relevant to their needs.

Hypothesis: If we provide designed promo blocks within the body we will see a lift in download conversions because the CTA will be more apparent to the reader. If we keep high-performing content

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Plugin is in a place and functioning
- [x] Automated cross-posting of all Firefox Frontier blogs is enabled

#### Tasks
- [x] Add/enable Medium plugin for Wordpress
- [x] Configure for cross-posting blogs from Firefox Frontier blog (WP) to  https://medium.com/@firefox
- [ ] Determine measurement component w. @rraue

**Comment by rraue** [comment]
We need to make sure, that all cross posted posts will have a canonical back to the original post on blog.mozilla.org on medium!

**Comment by rraue** [comment]
It looks like the wordpress plugin has this as a default, but we need to double check it: https://help.medium.com/hc/en-us/articles/217991468-SEO-and-duplicate-content

**Comment by craigcook** [comment]
The plugin has been active for a while and posts are appearing on Medium: https://medium.com/the-official-unofficial-firefox-blog

However, all languages are appearing on Medium, each one appearing as a standalone article, and I'm not sure if that's desirable... or if it's possible to prevent it. 

WordPress doesn't really support more than one language for one blog. We use a plugin to (WordPress Multi-Lingual) "fake" a multilingual site, but each post in WordPress is still just a post in the stream. The plugin filters that stream on the blog itself to keep the languages separate and establish connections between equivalent translations, but evidently when they get syndicated to Medium it's all just one unfiltered stream.
